[package]
name = "music21-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
derivative = "2.2.0"
fraction = "0.15.3"
itertools = "0.14.0"
lazy_static = "1.5.0"
num = "0.4.3"
num-traits = "0.2.19"
