pub(crate) const ORDINAL_TYPE_FROM_NUM: [&str; 16] = [
    "duplex-maxima",
    "maxima",
    "longa",
    "breve",
    "whole",
    "half",
    "quarter",
    "eighth",
    "16th",
    "32nd",
    "64th",
    "128th",
    "256th",
    "512th",
    "1024th",
    "2048th",
];
