#[derive(Debug, Copy, Clone)]
pub(crate)  enum Ordinal {
    Zeroth = 0,
    First = 1,
    Second = 2,
    Third = 3,
    Fourth = 4,
    Fifth = 5,
    Sixth = 6,
    Seventh = 7,
    Eighth = 8,
    Ninth = 9,
    Tenth = 10,
    Eleventh = 11,
    Twelfth = 12,
    Thirteenth = 13,
    Fourteenth = 14,
    Fifteenth = 15,
    Sixteenth = 16,
    Seventeenth = 17,
    Eighteenth = 18,
    Nineteenth = 19,
    Twentieth = 20,
    TwentyFirst = 21,
    TwentySecond = 22,
}

impl Ordinal {
    pub(crate)  fn from_string(value: &str) -> Option<Ordinal> {
        match value.to_lowercase().as_str() {
            "zeroth" => Some(Ordinal::Zeroth),
            "first" => Some(Ordinal::First),
            "second" => Some(Ordinal::Second),
            "third" => Some(Ordinal::Third),
            "fourth" => Some(Ordinal::Fourth),
            "fifth" => Some(Ordinal::Fifth),
            "sixth" => Some(Ordinal::Sixth),
            "seventh" => Some(Ordinal::Seventh),
            "eighth" => Some(Ordinal::Eighth),
            "ninth" => Some(Ordinal::Ninth),
            "tenth" => Some(Ordinal::Tenth),
            "eleventh" => Some(Ordinal::Eleventh),
            "twelfth" => Some(Ordinal::Twelfth),
            "thirteenth" => Some(Ordinal::Thirteenth),
            "fourteenth" => Some(Ordinal::Fourteenth),
            "fifteenth" => Some(Ordinal::Fifteenth),
            "sixteenth" => Some(Ordinal::Sixteenth),
            "seventeenth" => Some(Ordinal::Seventeenth),
            "eighteenth" => Some(Ordinal::Eighteenth),
            "nineteenth" => Some(Ordinal::Nineteenth),
            "twentieth" => Some(Ordinal::Twentieth),
            "twenty-first" => Some(Ordinal::TwentyFirst),
            "twenty-second" => Some(Ordinal::TwentySecond),
            _ => None,
        }
    }

    pub(crate)  fn to_string(&self) -> String {
        match self {
            Ordinal::Zeroth => "zeroth".to_string(),
            Ordinal::First => "first".to_string(),
            Ordinal::Second => "second".to_string(),
            Ordinal::Third => "third".to_string(),
            Ordinal::Fourth => "fourth".to_string(),
            Ordinal::Fifth => "fifth".to_string(),
            Ordinal::Sixth => "sixth".to_string(),
            Ordinal::Seventh => "seventh".to_string(),
            Ordinal::Eighth => "eighth".to_string(),
            Ordinal::Ninth => "ninth".to_string(),
            Ordinal::Tenth => "tenth".to_string(),
            Ordinal::Eleventh => "eleventh".to_string(),
            Ordinal::Twelfth => "twelfth".to_string(),
            Ordinal::Thirteenth => "thirteenth".to_string(),
            Ordinal::Fourteenth => "fourteenth".to_string(),
            Ordinal::Fifteenth => "fifteenth".to_string(),
            Ordinal::Sixteenth => "sixteenth".to_string(),
            Ordinal::Seventeenth => "seventeenth".to_string(),
            Ordinal::Eighteenth => "eighteenth".to_string(),
            Ordinal::Nineteenth => "nineteenth".to_string(),
            Ordinal::Twentieth => "twentieth".to_string(),
            Ordinal::TwentyFirst => "twenty-first".to_string(),
            Ordinal::TwentySecond => "twenty-second".to_string(),
        }
    }

    pub(crate)  fn from_number(num: i32) -> Option<Ordinal> {
        match num {
            0 => Some(Ordinal::Zeroth),
            1 => Some(Ordinal::First),
            2 => Some(Ordinal::Second),
            3 => Some(Ordinal::Third),
            4 => Some(Ordinal::Fourth),
            5 => Some(Ordinal::Fifth),
            6 => Some(Ordinal::Sixth),
            7 => Some(Ordinal::Seventh),
            8 => Some(Ordinal::Eighth),
            9 => Some(Ordinal::Ninth),
            10 => Some(Ordinal::Tenth),
            11 => Some(Ordinal::Eleventh),
            12 => Some(Ordinal::Twelfth),
            13 => Some(Ordinal::Thirteenth),
            14 => Some(Ordinal::Fourteenth),
            15 => Some(Ordinal::Fifteenth),
            16 => Some(Ordinal::Sixteenth),
            17 => Some(Ordinal::Seventeenth),
            18 => Some(Ordinal::Eighteenth),
            19 => Some(Ordinal::Nineteenth),
            20 => Some(Ordinal::Twentieth),
            21 => Some(Ordinal::TwentyFirst),
            22 => Some(Ordinal::TwentySecond),
            _ => None,
        }
    }
}
